def solution(msg):
    answer = []
    char_table = {}

    for i in range(1, 27):
        char_table[chr(i+64)] = i
    
    w = msg[0]
    # 현재 입력(w)과 다음 글자(c)를 받아옴.
    # 합쳐서 없으면 현재 자리를 일단 출력 + 두개 합쳐서 사전에 등록
    # 이후 w를 c로 바꾸고 다음 글자를 c에 받아옴.
    # 만약 다음글자가 없으면 w에 해당하는 인덱스를 출력하고 종료함.
    
    for i in range(1, len(msg)):
        c = msg[i]
        if w+c in char_table:
            w = w+c
        else:
            answer.append(char_table[w])
            char_table[w+c] = len(char_table)+1
            w = c
        if i == len(msg)-1:
            answer.append(char_table[w])
            return answer
        
    # 길이가 1인 경우 for loop 자체를 돌지 못하기에 결과가 None으로 나오는 문제가 생김.
    # 항상 극단적인 경우를 고려해서 문제를 풀도록 해야 함.
    if len(msg) == 1:
        answer = [char_table[msg]]
        return answer

print(solution("KAKAO"))
print(solution("TOBEORNOTTOBEORTOBEORNOT"))
print(solution("ABABABABABABABAB"))
print(solution("THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS"))
print(solution("I"))